Wanup\CmsBundle\Entity\Tag:
    type: entity
    table: tag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        post:
            targetEntity: Post
            cascade: {  }
            fetch: LAZY
            mappedBy: tag
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
